#!/bin/bash
# Export the OpenOS userland SDK/sysroot used by the Chromium porting chain.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/target"
SDK_DIR="${OPENOS_SDK_DIR:-$BUILD/openos-sdk}"
USR="$ROOT/src/user"
KINC="$ROOT/src/kernel/include"
CC="${OPENOS_CC:-gcc}"
AR="${OPENOS_AR:-ar}"

require_tool() {
    local tool="$1"
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "ERROR: required tool '$tool' was not found." >&2
        exit 1
    fi
}

copy_if_exists() {
    local src="$1"
    local dst="$2"
    if [ -f "$src" ]; then
        cp "$src" "$dst"
    fi
}

require_tool "$CC"
require_tool "$AR"
require_tool ld

rm -rf "$SDK_DIR"
mkdir -p "$SDK_DIR/include/openos" "$SDK_DIR/lib" "$SDK_DIR/crt" "$SDK_DIR/ld" "$SDK_DIR/bin" "$BUILD"

# Public userland headers. Keep the export narrow and explicit: this is the ABI
# surface expected by Chromium-side platform glue, not a Linux-compatible sysroot.
for header in "$USR"/*.h; do
    [ -f "$header" ] || continue
    cp "$header" "$SDK_DIR/include/openos/"
done
copy_if_exists "$KINC/version.h" "$SDK_DIR/include/openos/version.h"

cp "$USR/user.ld" "$SDK_DIR/ld/user.ld"

# Build the OpenOS user entry object in the same freestanding mode used by the
# image build. Chromium/Skia/V8 smoke targets link this before application code.
"$CC" -m32 -ffreestanding -nostdlib -fno-pie -fno-pic -O2 \
    -fno-stack-protector -fno-builtin \
    -I "$USR" -I "$KINC" \
    -c "$USR/crt0.c" -o "$SDK_DIR/crt/crt0.o"

# The current user ABI is mostly header/syscall based. Export placeholder static
# archives now so GN/Ninja link lines can be stable while the real libc/C++
# runtime archives grow over time.
printf 'void __openos_empty_archive_anchor(void) {}\n' > "$BUILD/openos-sdk-empty.c"
"$CC" -m32 -ffreestanding -nostdlib -fno-pie -fno-pic -O2 \
    -fno-stack-protector -fno-builtin \
    -c "$BUILD/openos-sdk-empty.c" -o "$BUILD/openos-sdk-empty.o"
for lib in libopenos.a libopenos_c.a libopenos_cxx.a; do
    "$AR" rcs "$SDK_DIR/lib/$lib" "$BUILD/openos-sdk-empty.o"
done
rm -f "$BUILD/openos-sdk-empty.c" "$BUILD/openos-sdk-empty.o"

cat > "$SDK_DIR/bin/openos-clang-i386.cfg" <<CFG
-target i386-openos-elf
-ffreestanding
-fno-pic
-fno-pie
-fno-PIE
-fno-stack-protector
-fno-exceptions
-fno-rtti
-nostdlib
-I$SDK_DIR/include/openos
-T$SDK_DIR/ld/user.ld
CFG

cat > "$SDK_DIR/manifest.txt" <<EOF_MANIFEST
OpenOS userland SDK
Target: i386-openos-elf
Generated by: scripts/export-openos-sdk.sh

Headers: $SDK_DIR/include/openos
CRT:     $SDK_DIR/crt/crt0.o
Linker:  $SDK_DIR/ld/user.ld
Libs:    $SDK_DIR/lib/libopenos.a $SDK_DIR/lib/libopenos_c.a $SDK_DIR/lib/libopenos_cxx.a

Baseline flags:
-target i386-openos-elf -ffreestanding -fno-pic -fno-pie -fno-PIE -fno-stack-protector -fno-exceptions -fno-rtti -nostdlib

Link order:
$SDK_DIR/crt/crt0.o <application objects> $SDK_DIR/lib/libopenos.a $SDK_DIR/lib/libopenos_c.a $SDK_DIR/lib/libopenos_cxx.a -T $SDK_DIR/ld/user.ld
EOF_MANIFEST

# Compatibility copies matching docs/chromium-build-chain.md expectations.
cp "$SDK_DIR/crt/crt0.o" "$BUILD/openos-user-crt0.o"
cp "$SDK_DIR/lib/libopenos.a" "$BUILD/libopenos.a"
cp "$SDK_DIR/lib/libopenos_c.a" "$BUILD/libopenos_c.a"
cp "$SDK_DIR/lib/libopenos_cxx.a" "$BUILD/libopenos_cxx.a"

printf 'OpenOS SDK exported: %s\n' "$SDK_DIR"
printf '  %s\n' "$BUILD/openos-user-crt0.o" "$BUILD/libopenos.a" "$BUILD/libopenos_c.a" "$BUILD/libopenos_cxx.a"
