<#
Generate OpenOS 16x16 CJK bitmap glyph table from a Windows font via GDI+.

It scans UTF-8 source files, renders every CJK/fullwidth codepoint with
System.Drawing, and writes src/kernel/generated/cjk_font.c.
#>
param(
    [string]$FontName = 'Microsoft YaHei',
    [int]$FontSize = 14,
    [string]$Out = 'src/kernel/generated/cjk_font.c',
    [string[]]$Scan = @('src/kernel/i18n.c'),
    [string]$ExtraChars = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.Drawing

function Add-Codepoint([System.Collections.Generic.HashSet[int]]$set, [int]$cp) {
    if ((($cp -ge 0x3400) -and ($cp -le 0x4DBF)) -or
        (($cp -ge 0x4E00) -and ($cp -le 0x9FFF)) -or
        (($cp -ge 0xF900) -and ($cp -le 0xFAFF)) -or
        (($cp -ge 0x3000) -and ($cp -le 0x303F)) -or
        (($cp -ge 0xFF00) -and ($cp -le 0xFFEF))) {
        [void]$set.Add($cp)
    }
}

function Add-TextCodepoints([System.Collections.Generic.HashSet[int]]$set, [string]$text) {
    for ($i = 0; $i -lt $text.Length; $i++) {
        $unit = [int][char]$text[$i]
        if (($unit -ge 0xD800) -and ($unit -le 0xDBFF) -and (($i + 1) -lt $text.Length)) {
            $low = [int][char]$text[$i + 1]
            if (($low -ge 0xDC00) -and ($low -le 0xDFFF)) {
                $cp = 0x10000 + (($unit - 0xD800) * 0x400) + ($low - 0xDC00)
                Add-Codepoint $set $cp
                $i++
                continue
            }
        }
        Add-Codepoint $set $unit
    }
}

$codepoints = New-Object 'System.Collections.Generic.HashSet[int]'
foreach ($path in $Scan) {
    if (Test-Path $path) {
        $resolved = Resolve-Path $path
        $text = [System.IO.File]::ReadAllText($resolved, [System.Text.Encoding]::UTF8)
        Add-TextCodepoints $codepoints $text
    }
}
if ($ExtraChars.Length -gt 0) {
    Add-TextCodepoints $codepoints $ExtraChars
}

$sorted = @($codepoints) | Sort-Object
if ($sorted.Count -eq 0) {
    throw 'No CJK/fullwidth codepoints found.'
}

$font = New-Object System.Drawing.Font($FontName, $FontSize, [System.Drawing.FontStyle]::Regular, [System.Drawing.GraphicsUnit]::Pixel)
$format = New-Object System.Drawing.StringFormat
$format.Alignment = [System.Drawing.StringAlignment]::Center
$format.LineAlignment = [System.Drawing.StringAlignment]::Center
$format.FormatFlags = $format.FormatFlags -bor [System.Drawing.StringFormatFlags]::NoClip

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('/* Auto-generated by scripts/generate_cjk_font.ps1. Do not edit by hand. */')
$lines.Add('#include "font.h"')
$lines.Add('#include "cjk_font.h"')
$lines.Add('')
$lines.Add('const font_cjk_glyph_t g_generated_cjk_glyphs[] = {')

foreach ($cp in $sorted) {
    $bmp = New-Object System.Drawing.Bitmap(16, 16, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.Clear([System.Drawing.Color]::Black)
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::SingleBitPerPixelGridFit
    $rect = New-Object System.Drawing.RectangleF(0, 0, 16, 16)
    $ch = [char]$cp
    $g.DrawString([string]$ch, $font, [System.Drawing.Brushes]::White, $rect, $format)
    $rows = New-Object System.Collections.Generic.List[string]
    for ($y = 0; $y -lt 16; $y++) {
        $bits = 0
        for ($x = 0; $x -lt 16; $x++) {
            $color = $bmp.GetPixel($x, $y)
            if ($color.R -ge 96) {
                $bits = $bits -bor (0x8000 -shr $x)
            }
        }
        $rows.Add(('0x{0:x4}u' -f $bits))
    }
    $g.Dispose()
    $bmp.Dispose()
    $lines.Add(('    {{ 0x{0:X4}u, {{ {1} }} }},' -f $cp, ($rows -join ',')))
}

$lines.Add('};')
$lines.Add('')
$lines.Add('const uint32_t g_generated_cjk_glyph_count =')
$lines.Add('    (uint32_t)(sizeof(g_generated_cjk_glyphs) / sizeof(g_generated_cjk_glyphs[0]));')
$lines.Add('')
$lines.Add(('const char g_generated_cjk_font_source[] = "{0}";' -f $FontName))

$outDir = Split-Path -Parent $Out
if ($outDir -and -not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
}
$outPath = if ([System.IO.Path]::IsPathRooted($Out)) { $Out } else { Join-Path (Get-Location) $Out }
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, ($lines -join "`n") + "`n", $utf8NoBom)
Write-Host ('generated {0} glyphs -> {1} using {2}' -f $sorted.Count, $outPath, $FontName)
