#!/usr/bin/env python3
"""Generate OpenOS 16x16 CJK bitmap glyph table from a real font.

This is the build-time path for the full CJK font backend.  It renders the
codepoints used by the zh-CN locale from a TrueType/OpenType/TTC font into a
compact C source table consumed by src/kernel/font.c.

Dependencies:
  - Pillow when running under Linux/macOS/Windows Python; or
  - use a pre-generated src/kernel/generated/cjk_font.c checked into the tree.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

WIDTH = 16
HEIGHT = 16


def collect_codepoints(paths: Sequence[Path]) -> List[int]:
    text = ""
    for path in paths:
        if path.exists():
            text += path.read_text(encoding="utf-8")
    cps = {
        ord(ch)
        for ch in text
        if (0x3400 <= ord(ch) <= 0x4DBF)
        or (0x4E00 <= ord(ch) <= 0x9FFF)
        or (0xF900 <= ord(ch) <= 0xFAFF)
        or (0x20000 <= ord(ch) <= 0x2FA1F)
        or (0x3000 <= ord(ch) <= 0x303F)
        or (0xFF00 <= ord(ch) <= 0xFFEF)
    }
    return sorted(cps)


def parse_codepoint_list(value: str) -> List[int]:
    out = []
    for part in re.split(r"[\s,;]+", value.strip()):
        if not part:
            continue
        if part.startswith(("U+", "u+")):
            out.append(int(part[2:], 16))
        elif part.startswith(("0x", "0X")):
            out.append(int(part, 16))
        elif len(part) == 1:
            out.append(ord(part))
        else:
            out.append(int(part, 16))
    return sorted(set(out))


def render_with_pillow(font_path: Path, codepoints: Iterable[int]) -> List[Tuple[int, List[int]]]:
    try:
        from PIL import Image, ImageDraw, ImageFont
    except Exception as exc:  # pragma: no cover - environment dependent
        raise RuntimeError(
            "Pillow is required to regenerate CJK glyphs. "
            "Install python3-pil or use the checked-in generated cjk_font.c."
        ) from exc

    # Size 16 keeps the kernel glyph ABI compact.  Try a few sizes to get the
    # cleanest bounding box, then center into 16x16.
    font = ImageFont.truetype(str(font_path), 16)
    glyphs: List[Tuple[int, List[int]]] = []
    for cp in codepoints:
        ch = chr(cp)
        img = Image.new("L", (WIDTH * 3, HEIGHT * 3), 0)
        draw = ImageDraw.Draw(img)
        try:
            bbox = draw.textbbox((0, 0), ch, font=font)
        except AttributeError:  # Pillow < 8
            w, h = draw.textsize(ch, font=font)
            bbox = (0, 0, w, h)
        gw = max(1, bbox[2] - bbox[0])
        gh = max(1, bbox[3] - bbox[1])
        x = (WIDTH - gw) // 2 - bbox[0]
        y = (HEIGHT - gh) // 2 - bbox[1]
        draw.text((x, y), ch, fill=255, font=font)
        rows: List[int] = []
        for y0 in range(HEIGHT):
            bits = 0
            for x0 in range(WIDTH):
                if img.getpixel((x0, y0)) >= 96:
                    bits |= 0x8000 >> x0
            rows.append(bits)
        glyphs.append((cp, rows))
    return glyphs


def write_c(out_path: Path, font_path: Path, glyphs: Sequence[Tuple[int, Sequence[int]]]) -> None:
    lines = []
    lines.append("/* Auto-generated by scripts/generate_cjk_font.py. Do not edit by hand. */")
    lines.append("#include \"font.h\"")
    lines.append("#include \"generated/cjk_font.h\"")
    lines.append("")
    lines.append("const font_cjk_glyph_t g_generated_cjk_glyphs[] = {")
    for cp, rows in glyphs:
        row_text = ",".join(f"0x{row:04x}u" for row in rows)
        lines.append(f"    {{ 0x{cp:04X}u, {{ {row_text} }} }},")
    lines.append("};")
    lines.append("")
    lines.append("const uint32_t g_generated_cjk_glyph_count =")
    lines.append("    (uint32_t)(sizeof(g_generated_cjk_glyphs) / sizeof(g_generated_cjk_glyphs[0]));")
    lines.append("")
    lines.append(f"const char g_generated_cjk_font_source[] = \"{font_path.as_posix()}\";")
    lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", type=Path, required=True, help="TTF/OTF/TTC font path")
    parser.add_argument("--out", type=Path, required=True, help="output C source path")
    parser.add_argument("--scan", type=Path, action="append", default=[], help="UTF-8 file to scan for glyphs")
    parser.add_argument("--chars", default="", help="extra characters / U+xxxx / hex codepoints")
    args = parser.parse_args(argv)

    cps = set(collect_codepoints(args.scan))
    if args.chars:
        cps.update(parse_codepoint_list(args.chars))
    if not cps:
        raise SystemExit("no CJK codepoints found")
    if not args.font.exists():
        raise SystemExit(f"font not found: {args.font}")
    glyphs = render_with_pillow(args.font, sorted(cps))
    write_c(args.out, args.font, glyphs)
    print(f"generated {len(glyphs)} glyphs -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
