#!/usr/bin/env python3
import pathlib
import sys

if len(sys.argv) < 3:
    print("usage: gen_embed_resources.py OUT_HEADER SYMBOL=PATH ...", file=sys.stderr)
    sys.exit(2)

out = pathlib.Path(sys.argv[1])
entries = []

for item in sys.argv[2:]:
    if "=" not in item:
        print(f"invalid resource argument: {item}", file=sys.stderr)
        sys.exit(2)
    symbol, path_text = item.split("=", 1)
    path = pathlib.Path(path_text)
    data = path.read_bytes()
    entries.append((symbol, path.as_posix(), data))

with out.open("w", encoding="utf-8") as f:
    f.write("#ifndef OPENOS_EMBED_TCC_RESOURCES_H\n")
    f.write("#define OPENOS_EMBED_TCC_RESOURCES_H\n\n")
    f.write("/* Auto-generated by tools/gen_embed_resources.py. */\n\n")
    for symbol, path, data in entries:
        f.write(f"static const unsigned char {symbol}[] = {{\n")
        for i in range(0, len(data), 12):
            chunk = data[i:i + 12]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        if not data:
            f.write("    0,\n")
        f.write("};\n")
        f.write(f"static const unsigned int {symbol}_len = {len(data)};\n")
        f.write(f"/* source: {path} */\n\n")
    f.write("#endif /* OPENOS_EMBED_TCC_RESOURCES_H */\n")
